<a href="https://colab.research.google.com/github/geovannathereza/curso-de-machine-learning/blob/main/atividade_casa_aula5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

arange

In [ ]:
arr1 = np.arange(10)

In [ ]:
arr2 = np.arange(10, 20)

In [ ]:
arr3 = np.arange(10, 20, 2)

In [ ]:
arr4 = np.arange(10, 20, 1.4)

linspace

In [ ]:
arr5 = np.linspace(10, 20, 11)

In [ ]:
arr6 = np.linspace(10, 20, 101)

In [ ]:
arr7 = np.linspace(0, np.pi, 100)

Criando a primeira matriz


In [ ]:
minhaMatriz = np.array([[1, 2, 3],
                        [4, 5, 6]])

Lembrando que você pode escrever apenas assim

In [ ]:
minhaMatriz = np.array([[1, 2, 3], [4, 5, 6]])
minhaMatriz

array([[1, 2, 3],
       [4, 5, 6]])

Podemos criar uma matriz a partir de uma lista

In [ ]:
minhaLista = [[13, 81, 22], [0, 34, 59], [21, 48, 94]]

Agora usaremos o np.matrix

In [ ]:
minhaMatriz = np.matrix(minhaLista)
minhaMatriz

matrix([[13, 81, 22],
        [ 0, 34, 59],
        [21, 48, 94]])

np.zeros: pode formar vetores e matrizes

vetor:

In [ ]:
x = np.zeros(3)
x

array([0., 0., 0.])

matriz:

In [ ]:
x = np.zeros((3,2))
x

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

Outra forma: sem armazenar em variáveis

vetor:

In [ ]:
print(np.zeros(3))

[0. 0. 0.]


matriz:

In [ ]:
print(np.zeros((3,2)))

[[0. 0.]
 [0. 0.]
 [0. 0.]]


np.ones

In [ ]:
x = np.ones((5,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

igualmente é possível para apenas um vetor

In [ ]:
y = np.ones(5)
y

array([1., 1., 1., 1., 1.])

Desafio: como obter uma matriz 4x4 apenas com números 8?

In [ ]:
matriz = np.array([[8, 8, 8, 8],
                   [8, 8, 8, 8],
                   [8, 8, 8, 8],
                   [8, 8, 8, 8]])

np.diag para formar matrizes:

os valores passados como parâmetro formam uma diagonal

In [ ]:
z = np.diag(np.array([1, 2, 3, 4, 5, 6]))
z

array([[1, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0],
       [0, 0, 0, 4, 0, 0],
       [0, 0, 0, 0, 5, 0],
       [0, 0, 0, 0, 0, 6]])

np.eye para formar matrizes

In [ ]:
y = np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

agora determinando o tipo int

In [ ]:
y = np.eye (5, dtype = int)
y

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

Verificando o shape(forma) de duas maneiras

In [ ]:
np.shape(minhaMatriz)

(3, 3)

In [ ]:
minhaMatriz.shape

(3, 3)

Verificando o tipo da matriz

In [ ]:
type(minhaMatriz)

numpy.matrix

Verificando o tipo dos dados da matriz

In [ ]:
minhaMatriz.dtype

dtype('int64')

Selecionando elementos de uma matriz:

In [ ]:
minhaMatriz[2, 1]

48

Selecionando a primeira linha da matriz

In [ ]:
print(minhaMatriz[0,:])

[[13 81 22]]


Selecionando a terceira coluna da matriz

In [ ]:
print(minhaMatriz[:,2])

[[22]
 [59]
 [94]]


Alterando um elemento da matriz

In [ ]:
minhaMatriz[1,0] = 100
minhaMatriz

matrix([[ 13,  81,  22],
        [100,  34,  59],
        [ 21,  48,  94]])

Obtendo a soma dos valores do array

In [ ]:
#como não tinha sido criado nenhum "meuArray" ou apenas "array"
#durante a atividade o código deu erro mas a sintaxe está correta.

np.sum(meuArray)

Obtendo o produto

In [ ]:
np.prod(meuArray)

Obtendo a soma acumulada

In [ ]:
np.cumsum(meuArray)

Obtendo o valor mínimo do array

In [ ]:
array.min()

Obtendo o valor máximo:

In [ ]:
array.max()

Operações com estatística básica

Obtendo a média dos valores do array

In [ ]:
np.mean(meuArray)

Obtendo a mediana

In [ ]:
np.median(meuArray)

Obtendo a variância dos valores

In [ ]:
np.var(meuArray)

Obtendo o desvio padrão dos valores

In [ ]:
np.std(meuArray)

Criar um array unidimensional usando arange com 20 elementos;

● “Varrer” o array para obter os pares;

● “Varrer” o array para obter os ímpares;

● Obter a média, a soma, o produto, a variância e o desvio padrão
do array.

● Saber se os valores são maiores que 5;

● Obter os valores maiores que 5.

In [6]:
desafioArray = np.arange(0, 20)


In [30]:
#varrer pares
print(desafioArray[2:20:2])

[ 2  4  6  8 10 12 14 16 18]


In [29]:
#varres impares
print(desafioArray[1:20:2])

[ 1  3  5  7  9 11 13 15 17 19]


In [18]:
np.mean(desafioArray)

9.5

In [19]:
np.sum(desafioArray)

190

In [20]:
np.prod(desafioArray)

0

In [21]:
np.var(desafioArray)

33.25

In [22]:
np.std(desafioArray)

5.766281297335398

In [23]:
print(desafioArray > 5)

[False False False False False False  True  True  True  True  True  True
  True  True  True  True  True  True  True  True]


In [24]:
print(desafioArray[6:20])

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19]
