<a href="https://colab.research.google.com/github/geovannathereza/curso-de-machine-learning/blob/main/aula6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
minhaLista = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [3]:
meuArray = np.array(minhaLista)

meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [4]:
meuArray

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
print(meuArray)

[0 1 2 3 4 5 6 7 8]


In [6]:
minhaLista = list(range(9))
minhaLista

[0, 1, 2, 3, 4, 5, 6, 7, 8]

In [7]:
array1 = np.array(range(9))
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
array2 = np.arange(9)
array2

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
array3 = np.arange(0, 10, 0.5)
array3

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [10]:
novoArray = np.around(array3)
novoArray

array([ 0.,  0.,  1.,  2.,  2.,  2.,  3.,  4.,  4.,  4.,  5.,  6.,  6.,
        6.,  7.,  8.,  8.,  8.,  9., 10.])

In [11]:
array3 = np.arange(0, 10, 0.5, dtype = int)
array3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [12]:
array4 = np.arange(12)

In [14]:
array4 = np.arange(12.)
array4

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [15]:
type(array4)

numpy.ndarray

In [16]:
array4.dtype

dtype('float64')

In [17]:
vetor1 = np.array([0, 1, 2, 3, 4])
print(vetor1)

[0 1 2 3 4]


In [18]:
vetor1[3]

3

In [19]:
vetor1[0:2]

array([0, 1])

In [20]:
print(vetor1[0:2])

[0 1]


In [21]:
s = np.array(['Python', 'Profissional', 'Java', 'Água'])
s

array(['Python', 'Profissional', 'Java', 'Água'], dtype='<U12')

In [22]:
s = np.array(['Python', 1464321315, 'Profissional', 'Java', 'Água'])
s

array(['Python', '1464321315', 'Profissional', 'Java', 'Água'],
      dtype='<U21')

In [23]:
vetor1[2] = 10
vetor1

array([ 0,  1, 10,  3,  4])

In [ ]:
vetor1[0] = 'Novo Elemento'
vetor1

In [25]:
vetor1[0] = 45.6
vetor1

array([45,  1, 10,  3,  4])